#!/usr/bin/env bash
# PreToolUse guard: block direct edits to generated or sensitive project files.
# project.yml is the source of truth; .pbxproj is generated. Secrets never get edited by Claude.
set +e
input=$(cat)
file=$(echo "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -n "$file" ] || exit 0
case "$file" in
  *.pbxproj|*.xcworkspace/*|*.xcscheme)
    echo "Blocked: $file is generated by XcodeGen. Edit project.yml and run 'make generate'." >&2; exit 2 ;;
  */Configs/Local.xcconfig|*/.env|*/.env.*|*.p12|*.mobileprovision|*/AuthKey_*.p8|*/.config/xcode-development/env)
    echo "Blocked: $file holds signing or secret data. Claude does not edit it." >&2; exit 2 ;;
esac
exit 0
